package cn.uc.yiqibang.beans;

import java.util.Date;

public class TComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.t_n_id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    private Integer tNId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.t_u_id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    private Integer tUId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.c_content
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    private String cContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.c_createtime
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    private Date cCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.c_thumbscount
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    private Integer cThumbscount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.id
     *
     * @return the value of t_comment.id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.id
     *
     * @param id the value for t_comment.id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.t_n_id
     *
     * @return the value of t_comment.t_n_id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public Integer gettNId() {
        return tNId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.t_n_id
     *
     * @param tNId the value for t_comment.t_n_id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public void settNId(Integer tNId) {
        this.tNId = tNId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.t_u_id
     *
     * @return the value of t_comment.t_u_id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public Integer gettUId() {
        return tUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.t_u_id
     *
     * @param tUId the value for t_comment.t_u_id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public void settUId(Integer tUId) {
        this.tUId = tUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.c_content
     *
     * @return the value of t_comment.c_content
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public String getcContent() {
        return cContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.c_content
     *
     * @param cContent the value for t_comment.c_content
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public void setcContent(String cContent) {
        this.cContent = cContent == null ? null : cContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.c_createtime
     *
     * @return the value of t_comment.c_createtime
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public Date getcCreatetime() {
        return cCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.c_createtime
     *
     * @param cCreatetime the value for t_comment.c_createtime
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public void setcCreatetime(Date cCreatetime) {
        this.cCreatetime = cCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.c_thumbscount
     *
     * @return the value of t_comment.c_thumbscount
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public Integer getcThumbscount() {
        return cThumbscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.c_thumbscount
     *
     * @param cThumbscount the value for t_comment.c_thumbscount
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public void setcThumbscount(Integer cThumbscount) {
        this.cThumbscount = cThumbscount;
    }
}