package cn.uc.yiqibang.beans;

public class TPic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.t_n_id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    private Integer tNId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.p_path
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    private String pPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.p_info
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    private String pInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.p_author
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    private String pAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic.p_source
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    private String pSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.id
     *
     * @return the value of t_pic.id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.id
     *
     * @param id the value for t_pic.id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.t_n_id
     *
     * @return the value of t_pic.t_n_id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public Integer gettNId() {
        return tNId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.t_n_id
     *
     * @param tNId the value for t_pic.t_n_id
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public void settNId(Integer tNId) {
        this.tNId = tNId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.p_path
     *
     * @return the value of t_pic.p_path
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public String getpPath() {
        return pPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.p_path
     *
     * @param pPath the value for t_pic.p_path
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public void setpPath(String pPath) {
        this.pPath = pPath == null ? null : pPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.p_info
     *
     * @return the value of t_pic.p_info
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public String getpInfo() {
        return pInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.p_info
     *
     * @param pInfo the value for t_pic.p_info
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public void setpInfo(String pInfo) {
        this.pInfo = pInfo == null ? null : pInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.p_author
     *
     * @return the value of t_pic.p_author
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public String getpAuthor() {
        return pAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.p_author
     *
     * @param pAuthor the value for t_pic.p_author
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public void setpAuthor(String pAuthor) {
        this.pAuthor = pAuthor == null ? null : pAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic.p_source
     *
     * @return the value of t_pic.p_source
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public String getpSource() {
        return pSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic.p_source
     *
     * @param pSource the value for t_pic.p_source
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    public void setpSource(String pSource) {
        this.pSource = pSource == null ? null : pSource.trim();
    }
}